name: JavaDoc Generation

on:
  pull_request:
    types:
      - closed

jobs:
  JDocGeneration:
    name: JavaDoc Generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Generate JavaDoc
        run: mvn -B javadoc::javadoc

      - name: Deploy JavaDoc
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./target/reports/apidocs
