name: Bonjour
on: [push] # Ce workflow se déclenche sur un push dans le dépôt
jobs:
  Salutations: # Nom du job : Salutations
  name: Salutations
  runs-on: ubuntu-latest # OS où s'exécute le job
  steps:
    - name: Hello #une tâche pour saluer
  env:
  personneASaluer: 'Mon voisin Totoro'
  run: echo "Bonjour ${personneASaluer}"